# -*- coding: utf-8 -*-
"""CodeAlpha_Amazon_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RErPsfEPsaHtqoJttHldqw9ArDtt_qP-

#TASK 2: Exploratory Data Analysis (EDA)
● Ask meaningful questions about the dataset before analysis.

● Explore the data structure, including variables and data types.

● Identify trends, patterns and anomalies within the data.
● Test hypotheses and validate assumptions using statistics and visualization.

● Detect potential data issues or problems to address in further analysis.

**Import Libraries**
"""

import pandas as pd
import numpy as np

""" **Load Dataset**"""

from google.colab import files

uploaded = files.upload()

import io
import zipfile

# Access the content of the uploaded zip file
zip_content = uploaded['ratings_Electronics.csv (1).zip']

# Read the zip content from memory
with zipfile.ZipFile(io.BytesIO(zip_content), 'r') as zf:
    # Assuming the CSV file inside is named 'ratings_Electronics.csv'
    with zf.open('ratings_Electronics.csv') as f:
        # Read without a header, then assign column names
        df = pd.read_csv(f, header=None)
        df.columns = ['user_id', 'product_id', 'rating', 'timestamp']

"""**Display First 3 Rows**"""

print("--- Dataset Sample ---")
# Display relevant columns from the actual dataset
display(df[['user_id', 'product_id', 'rating', 'timestamp']].head(3))

"""**Select Columns**"""

df[['user_id', 'product_id', 'rating', 'timestamp']]

"""**Check Dataset Information**"""

print("\n--- Dataset Info ---")
df.info()

"""**Keep Required Columns**"""

columns_to_keep = ['user_id', 'product_id', 'rating', 'timestamp']

"""**Remove Unnecessary Columns and Missing Values**"""

df = df[columns_to_keep].dropna()

"""**Clean Rating Column**"""

# The 'rating' column is already float64, no string extraction is needed.
# If you intend to ensure it's a float, this line can be used, though it's redundant:
# df['rating'] = df['rating'].astype(float)

"""**Extract Number**"""

# This line caused a SyntaxError because it's incomplete.
# It needs to be applied to a Series (e.g., df['column_name'].str.extract(...)).
# However, your 'rating' column is already a float, so string extraction is not needed.
# If you meant to extract numbers from a different column, please specify that column.

"""**Convert to Decimal Number**"""

# .astype(float) # This line caused a SyntaxError because it's incomplete.
# It needs to be applied to a Series (e.g., df['column_name'].astype(float)).
# Your 'rating' column is already a float, so this specific conversion is not needed.
# If you meant to convert a different column, please specify that column.

"""**Remove Old Rating Column**"""

# df = df.drop(columns=['average_review_rating']) # This line caused a KeyError because 'average_review_rating' column does not exist in the DataFrame.

"""**Success Message**"""

print("Data Cleaned Successfully! Missing rows dropped.")

"""**Count Rows**"""

print(f"Total clean rows ready for analysis: {df.shape[0]}")

df.shape

df.shape[0]

"""**Show Cleaned Data**"""

df.head()

# The original code caused a KeyError because columns like 'average_review_rating', 'product_name', 'price', and 'customer_reviews' do not exist in the DataFrame.
# The 'rating' column is already numeric.
# Displaying the head of the existing DataFrame to show the cleaned data with available columns.
display(df.head(3))