# -*- coding: utf-8 -*-
"""Task 3: Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12f-3Hl_zAIeoZfvxbDBTzRohilfXlLzz

#TASK 3: Data Visualization
● Transform raw data into visual formats like charts, graphs, and dashboards.

● Use tools like Matplotlib, Seaborn, or Tableau for creating visuals.

● Design visuals that enhance understanding and reveal insights clearly.

● Craft compelling data stories that support decision-making.

● Build a strong portfolio with impactful and well-designed visualizations.

**Upload Dataset to Google Colab**
"""

import pandas as pd

df = pd.read_csv('netflix_titles.csv')
df.head()

"""**Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

"""**Basic Data Understanding**"""

print(df.shape)

print(df.info())

print(df.isnull().sum())

"""**Visualization 1 – Movies vs TV Shows**"""

plt.figure(figsize=(8,5))

sns.countplot(x='type', data=df)

plt.title("Movies vs TV Shows")
plt.show()

"""**Visualization 2 – Content Rating Distribution**"""

plt.figure(figsize=(10,5))

sns.countplot(y='rating',
              data=df,
              order=df['rating'].value_counts().index)

plt.title("Distribution of Ratings")
plt.show()

"""**Visualization 3 – Top 10 Countries**"""

country_count = df['country'].value_counts().head(10)

plt.figure(figsize=(10,6))

country_count.plot(kind='bar')

plt.title("Top 10 Countries Producing Netflix Content")

plt.xlabel("Country")
plt.ylabel("Count")

plt.show()

"""**Visualization 4 – Content Added Over Time**"""

df['date_added'] = pd.to_datetime(df['date_added'], format='mixed', dayfirst=False, errors='coerce')

df['year_added'] = df['date_added'].dt.year

plt.figure(figsize=(10,5))

sns.countplot(x='year_added',
              data=df,
              order=df['year_added'].value_counts().index.sort_values())

plt.xticks(rotation=45)

plt.title("Content Added Per Year")

plt.show()

"""**Visualization 5 – Top Genres**"""

genres = df['listed_in'].str.split(', ').explode()

top_genres = genres.value_counts().head(10)

plt.figure(figsize=(10,6))

sns.barplot(x=top_genres.values,
            y=top_genres.index)

plt.title("Top 10 Genres")

plt.show()

"""**Create Dashboard Layout**"""

fig, axes = plt.subplots(2,2, figsize=(14,10))

sns.countplot(x='type', data=df, ax=axes[0,0])

sns.countplot(y='rating',
              data=df,
              order=df['rating'].value_counts().head(10).index,
              ax=axes[0,1])

country_count.plot(kind='bar',
                   ax=axes[1,0])

top_genres.head(5).plot(kind='bar',
                        ax=axes[1,1])

plt.tight_layout()
plt.show()