# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tt9rdYWJYaBEWf8oy-czZALZKNlZT0hm

#TASK 4: Sentiment Analysis
● 1. Analyze text data to classify it as positive, negative or neutra.

● 2. Use NLP techniques and lexicons to detect specific emotions.

● 3. Apply analysis on data from sources like Amazon reviews, social media, and news sites.

 ● 4. Understand public opinion and trends through sentiment patterns.

● 5. Use results to inform marketing, product development, or social insights

**Import Libraries**
"""

# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

"""**Load Dataset**"""

df = pd.read_csv('Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv')

df.head()

df.columns

"""**Select Review Text**"""

reviews = df[['reviews.text', 'reviews.rating']]

reviews.head()

"""*Remove missing values:*"""

reviews = reviews.dropna()

reviews.shape

"""**Create Sentiment Labels**

*Convert ratings into:*

Positive = 4 or 5 stars

Neutral = 3 stars

Negative = 1 or 2 stars


"""

def sentiment_label(rating):
    if rating >= 4:
        return 'Positive'
    elif rating == 3:
        return 'Neutral'
    else:
        return 'Negative'

reviews['Sentiment'] = reviews['reviews.rating'].apply(sentiment_label)

reviews.head()

"""**Visualize Sentiment Distribution**"""

plt.figure(figsize=(8,5))

sns.countplot(
    x='Sentiment',
    data=reviews,
    order=['Positive','Neutral','Negative']
)

plt.title('Sentiment Distribution')
plt.show()

"""**Apply NLP Sentiment Analysis**"""

sia = SentimentIntensityAnalyzer()

reviews['compound_score'] = reviews['reviews.text'].apply(
    lambda x: sia.polarity_scores(str(x))['compound']
)

reviews[['reviews.text','compound_score']].head()

"""**Classify Reviews Using NLP**"""

def vader_sentiment(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

reviews['Predicted_Sentiment'] = reviews['compound_score'].apply(vader_sentiment)

reviews.head()

"""**Compare Results**"""

pd.crosstab(
    reviews['Sentiment'],
    reviews['Predicted_Sentiment']
)

"""**Visualize NLP Results**"""

plt.figure(figsize=(8,5))

sns.countplot(
    x='Predicted_Sentiment',
    data=reviews,
    order=['Positive','Neutral','Negative']
)

plt.title('Predicted Sentiment Distribution')
plt.show()

"""**Emotion Scores**"""

def get_scores(text):
    return sia.polarity_scores(str(text))

emotion_scores = reviews['reviews.text'].apply(get_scores)

emotion_df = pd.DataFrame(list(emotion_scores))

emotion_df.head()

"""**Visualize Emotion Components**"""

avg_scores = emotion_df.mean()

plt.figure(figsize=(8,5))

avg_scores.plot(kind='bar')

plt.title('Average Emotion Scores')
plt.ylabel('Score')
plt.show()

"""**Top Positive Reviews**"""

reviews.sort_values(
    by='compound_score',
    ascending=False
)[['reviews.text','compound_score']].head(10)

"""**Top Negative Reviews**"""

reviews.sort_values(
    by='compound_score',
    ascending=True
)[['reviews.text','compound_score']].head(10)